apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: banking-app
  labels:
    app: account
    service: account
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: account
