apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: avatar
  namespace: banking-app
spec:
  hosts:
  - api.dicebear.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
